all:
	g++ -Wall -Werror -Wfatal-errors -o test1 AmericanCallOption.cpp Option.cpp BlackScholesMCPricer.cpp EuropeanDigitalOption.cpp AmericanOption.cpp BlackScholesPricer.cpp EuropeanDigitalPutOption.cpp AmericanPutOption.cpp CRRPricer.cpp EuropeanVanillaOption.cpp PutOption.cpp CallOption.cpp MT.cpp test1.cpp BinaryTree.cpp EuropeanDigitalCallOption.cpp AsianOption.cpp AsianCallOption.cpp AsianPutOption.cpp
clean:
	rm -f main