all:
	g++ -Wall -Werror -Wfatal-errors -o test 1 AmericanCallOption.cpp Option.cpp BlackScholesMCPricer.cpp EuropeanDigitalOption.cpp AmericanOption.cpp Project_C++.cpp BlackScholesPricer.cpp EuropeanDigitalPutOption.cpp AmericanPutOption.cpp CRRPricer.cpp EuropeanVanillaOption.cpp PutOption.cpp CallOption.cpp MT.cpp test1.cpp test2.cpp BinaryTree.cpp EuropeanDigitalCallOption.cpp test3.cpp
clean:
	rm -f main